# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    logger_ws:
        class: AppBundle\Channels\WSChannel
        arguments: ["@logger"]
        tags:
            - { name: "monolog.logger", channel: "api_ws"}

    processor:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor }

    talkative_processor:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }

    talkative_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            # Adds the file:line_number where the log is called
            - "[%%datetime%%] %%channel%%.%%level_name%%: [%%extra.file%%:%%extra.line%%] %%message%% %%context%% %%extra%%\n"
